---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y jq
  build:
    commands:
      - set -ev
      - /bin/bash ./scripts/build_docker.sh
