---
version: 0.2
phases:
  install:
    commands:
      - /bin/bash scripts/configure_codebuild_image.sh
  build:
    commands:
      - set -e
      - TEST_COMMAND=${TEST_COMMAND:-"test"}
      - AL_TEST_COMMAND=${AL_TEST_COMMAND:-"test:auditlogs"}
      - echo "Trying to acquire a build lock"
      - LOCK_PREFIX=${DEPLOY_ENV:-sandbox}
      - python3 ./scripts/build_locks.py acquire ${LOCK_PREFIX}-ci-codebuild-concurrency ${DEPLOY_ENV}-${WORKSPACE} 3600 7200 > /tmp/.lock_token
      - echo "Build lock acquired"
      - export OLD_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export OLD_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - temp_role=$(aws sts assume-role --role-session-name "next" --role-arn "${ASSUME_ROLE_ARN}")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - openvpn --config ~/cjse-${WORKSPACE}-config.ovpn --daemon
      - STACK_TYPE=next make setup-e2e-tests
      - npm i
      - source ./workspaces/${WORKSPACE}.env
      - CI=true RECORD=true npm run ${TEST_COMMAND}
      - CI=true RECORD=true MESSAGE_ENTRY_POINT=s3 npm run ${AL_TEST_COMMAND}
  post_build:
    commands:
      - unset AWS_SESSION_TOKEN
      - export AWS_ACCESS_KEY_ID=${OLD_AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${OLD_AWS_SECRET_ACCESS_KEY}
      - echo "Releasing build lock"
      - LOCK_PREFIX=${DEPLOY_ENV:-sandbox}
      - python3 ${CODEBUILD_SRC_DIR}/scripts/build_locks.py release ${LOCK_PREFIX}-ci-codebuild-concurrency ${DEPLOY_ENV}-${WORKSPACE} $(cat /tmp/.lock_token)
      - echo "Build lock released"
      - echo "Storing artifacts"
      - for file in ./screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - mkdir ./saved_artifacts
      - mv ./screenshots/*.tar.gz ./saved_artifacts/
      - aws s3 sync ./saved_artifacts s3://pathtolive-ci-codebuild/${WORKSPACE}-recordings/$(date +"%Y-%m-%dT%H:%M")/
