---
version: 0.2
phases:
  install:
    commands:
      - /bin/bash scripts/configure_codebuild_image.sh
  build:
    commands:
      - set -e
      - echo "Trying to acquire a build lock"
      - python3 ./scripts/build_locks.py acquire sandbox-ci-codebuild-concurrency ${WORKSPACE}-sandbox_a 3600 7200 > /tmp/.lock_token
      - echo "Build lock acquired"
      - export OLD_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export OLD_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - temp_role=$(aws sts assume-role --role-session-name "next" --role-arn "${ASSUME_ROLE_ARN}")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - openvpn --config ~/cjse-${WORKSPACE}-config.ovpn --daemon
      - export STACK_TYPE="$(echo $WORKSPACE | sed 's/dev-//g')"
      - make setup-e2e-tests
      - npm i
      - source ./workspaces/${WORKSPACE}.env
      - CI=true npm run test
  post_build:
    commands:
      - unset AWS_SESSION_TOKEN
      - export AWS_ACCESS_KEY_ID=${OLD_AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${OLD_AWS_SECRET_ACCESS_KEY}
      - echo "Releasing build lock"
      - python3 ${CODEBUILD_SRC_DIR}/scripts/build_locks.py release sandbox-ci-codebuild-concurrency ${WORKSPACE}-sandbox_a $(cat /tmp/.lock_token)
      - echo "Build lock released"
