---

version: 0.2
phases:
  install:
    commands:
      - /bin/bash scripts/configure_codebuild_image.sh
  build:
    commands:
      - set -e
      - echo "Trying to acquire a build lock"
      - LOCK_PREFIX=${DEPLOY_ENV:-sandbox}
      - python3 ./scripts/build_locks.py acquire ${LOCK_PREFIX}-ci-codebuild-concurrency ${DEPLOY_ENV}-${WORKSPACE} 3600 7200 > /tmp/.lock_token
      - echo "Build lock acquired"
      - export OLD_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export OLD_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - temp_role=$(aws sts assume-role --role-session-name "next" --role-arn "${ASSUME_ROLE_ARN}")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - openvpn --config ~/cjse-${WORKSPACE}-config.ovpn --daemon
      - STACK_TYPE=next make setup-e2e-tests
      - npm i
      - sed 's/export //g' < ./workspaces/${WORKSPACE}.env > ./loadtest/env/${WORKSPACE}.env
      - cp loadtest/config.sample.json loadtest/config.json
      - sed -i 's/local-loadtest.env/${WORKSPACE}.env/g' loadtest/config.json
      - sed -i 's/90/600/g' loadtest/config.json
      - sed -i 's/2/5/g' loadtest/config.json
      - make loadtest
  post_build:
    commands:
      - unset AWS_SESSION_TOKEN
      - export AWS_ACCESS_KEY_ID=${OLD_AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${OLD_AWS_SECRET_ACCESS_KEY}
      - echo "Releasing build lock"
      - LOCK_PREFIX=${DEPLOY_ENV:-sandbox}
      - python3 ${CODEBUILD_SRC_DIR}/scripts/build_locks.py release ${LOCK_PREFIX}-ci-codebuild-concurrency ${DEPLOY_ENV}-${WORKSPACE} $(cat /tmp/.lock_token)
      - echo "Build lock released"
...