config:
  target: "https://localhost:4443"
  processor: "./processor.js"
  environments:
    dev:
      phases:
        - duration: 1
          arrivalCount: 1
    test:
      phases:
        - duration: 60
          arrivalRate: 5
          name: Warm up
          maxVusers: 10
        - duration: 60
          arrivalRate: 5
          rampTo: 50
          maxVusers: 300
          name: Ramp up load
        - duration: 600
          arrivalRate: 50
          maxVusers: 300
          name: Sustained load
before:
  flow:
    - function: cleanupAllUsers
after:
  flow:
    - function: cleanupAllUsers
scenarios:
  - name: "Log in and load Bichard"
    beforeScenario: createUser
    afterScenario: cleanupUser
    flow:
      - get:
          url: "/"
      - think: 1
      - get:
          url: "/users/login"
          capture:
            - selector: input[name="CSRFToken"]
              attr: value
              as: csrfToken
      - think: 5
      - post:
          url: "/users/login"
          form:
            CSRFToken: "{{ csrfToken }}"
            emailAddress: "{{ email }}"
      - think: 10
      - get:
          url: /users/login/verify?token={{ token }}
          beforeRequest: generateVerifyToken
          capture:
            - selector: input[name="CSRFToken"]
              attr: value
              as: csrfVerifyToken
      - think: 5
      - post:
          url: "/users/login/verify"
          form:
            CSRFToken: "{{ csrfVerifyToken }}"
            password: password
      - think: 5
      - get:
          url: /users
      - think: 5
      - loop:
          - get:
              url: /bichard-ui/InitialRefreshList
          - think: 5
        count: 20
