# will circle ci pick this up now?
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  build-ci:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - 3d:e6:7f:cd:d1:2b:35:a5:71:da:87:12:c2:0b:0b:44
      - run:
          command: ssh-add -D
      - run:
          command: ssh-add ~/.ssh/id_rsa_3de67fcdd12b35a571da8712c20b0b44
      - run:
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next.git ~/bichard7-next
          name: Clone Bichard7 Next
      - run:
          command: |
            cd ~/bichard7-next
            make build-ci
          name: Build project
      - persist_to_workspace:
          root: ~/
          paths: bichard7-next
  test-next:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      STACK_TYPE: next
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: docker network prune -f
          name: Clear out the networks before we start our Docker services
      - run:
          command: |
            cd ~/bichard7-next
            make run-all-no-bc -j 4
          name: Run docker services (except BeanConnect)
      - run:
          name: Fetch the PNC Emulator image
          command: |
            cd ~/bichard7-next
            bash scripts/fetch_pncemulator_docker.sh
      - run:
          name: Fetch the BeanConnect image
          command: |
            cd ~/bichard7-next
            bash scripts/fetch_beanconnect_docker.sh
      - run:
          command: |
            cd ~/bichard7-next
            make run-beanconnect
          name: Run BeanConnect and PNC Emulator docker services
      - run:
          name: Wait for Websphere
          command: |
            cd ~/bichard7-next
            ./scripts/was/wait_for_websphere.sh
      - checkout
      - run:
          name: Build E2E tests
          command: make build
      - run:
          name: Run E2E tests
          command: |
            cd ~/bichard7-next
            WORKSPACE=local-next make e2e-tests

  test-baseline:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      STACK_TYPE: baseline
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: docker network prune -f
          name: Clear out the networks before we start our Docker services
      - run:
          command: |
            cd ~/bichard7-next
            make run-all-baseline-no-bc -j 4
          name: Run docker services (except BeanConnect)
      - run:
          name: Fetch the PNC Emulator image
          command: |
            cd ~/bichard7-next
            bash scripts/fetch_pncemulator_docker.sh
      - run:
          name: Fetch the BeanConnect image
          command: |
            cd ~/bichard7-next
            bash scripts/fetch_beanconnect_docker.sh
      - run:
          command: |
            cd ~/bichard7-next
            make run-beanconnect
          name: Run BeanConnect and PNC Emulator docker services
      - run:
          name: Wait for Websphere
          command: |
            cd ~/bichard7-next
            ./scripts/was/wait_for_websphere.sh
      - run:
          name: Wait for DB2
          command: |
            cd ~/bichard7-next
            ./scripts/db/wait_for_db.sh
      - checkout
      - run:
          name: Build E2E tests
          command: make build
      - run:
          name: Run E2E tests
          command: |
            cd ~/bichard7-next
            WORKSPACE=local-baseline make e2e-tests
workflows:
  version: 2

  deploy:
    jobs:
      - build-ci
      - test-next:
          requires:
            - build-ci
      - test-baseline:
          requires:
            - build-ci
