version: 2.1

orbs:
  node: circleci/node@5.2.0

commands:
  ################### Helpers
  checkout_core:
    steps:
      - run:
          name: Clone bichard7-next-core
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-core.git ~/bichard7-next-core
      - run:
          name: Install dependency
          working_directory: ~/bichard7-next-core
          command: npm i
      - run:
          name: Build core
          working_directory: ~/bichard7-next-core
          command: npm run build

  build_core_images:
    steps:
      - run:
          name: Build message forwarder image
          working_directory: ~/bichard7-next-core
          command: docker-compose -f environment/docker-compose.yml build message-forwarder

  build_audit_logging_images:
    steps:
      - run:
          name: Clone bichard7-next-audit-logging
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-audit-logging.git ~/bichard7-next-audit-logging
      - run:
          name: Build audit logging images
          working_directory: ~/bichard7-next-audit-logging
          command: make build-api-server build-event-handler-server

  run_test_chunk:
    steps:
      - run:
          name: Run test chunk
          command: |
            CHUNK=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings) \
            npm run test:chunk

  save_artifacts:
    steps:
      - run:
          name: Compress the artifacts for easier downloading
          when: always
          command: for file in ./screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - run:
          name: Create the saved_artifacts directory
          when: always
          command: mkdir ./saved_artifacts;
      - run:
          name: Move the gzipped files across
          when: always
          command: mv ./screenshots/*.tar.gz ./saved_artifacts/
      - store_artifacts:
          path: /home/circleci/project/saved_artifacts
      - store_test_results:
          path: /home/circleci/project/test-results.xml

  node_install:
    steps:
      - restore_cache:
          name: Restore nvm cache
          keys:
            # Invalidate the cache based on architecture, the version of Node defined in `nvmrc`
            - v1-nvm-cache-{{ arch }}-{{ checksum ".nvmrc" }}
      - run: nvm install
      - save_cache:
          name: Save nvm cache
          key: v1-nvm-cache-{{ arch }}-{{ checksum ".nvmrc" }}
          paths:
            - /opt/circleci/.nvm/.cache

  set_locale:
    steps:
      - run:
          name: Set GB locale
          working_directory: ~/bichard7-next-core
          command: bash .circleci/scripts/set-locale.sh

  install_ms_edge:
    steps:
      - run:
          name: Configure apt cache
          command: |
              echo 'APT::Keep-Downloaded-Packages "true";' >/etc/apt/apt.conf.d/01keep-debs
              echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' >>/etc/apt/apt.conf.d/01keep-debs
      - run:
          name: Remove apt cache purge configuration
          command: rm /etc/apt/apt.conf.d/docker-clean
      - restore_cache:
          keys:
              - ubuntu-package-cache-{{ checksum ".circleci/config.yml" }}
              - ubuntu-package-cache
      - run:
          name: Install MS Edge (dev)
          command: bash .circleci/scripts/install-ms-edge-on-linux.sh
      - run:
          name: Clean unneeded packages from cache
          command: apt autoclean
      - save_cache:
          key: ubuntu-package-cache-{{ checksum ".circleci/config.yml" }}
          paths:
              - "/var/cache/apt/archives"

  ################### Services
  start_bichard7_legacy:
    parameters:
      ENABLE_PHASE_2:
        default: "true"
        type: string
      ENABLE_PHASE_3:
        default: "true"
        type: string
    steps:
      - run: bash scripts/fetch_docker_image.sh nodejs-20-2023 # required for message-forwarder in core
      - build_core_images
      - build_audit_logging_images
      - run:
          name: Start bichard7 legacy
          working_directory: ~/bichard7-next-core
          command: |
            ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> ENABLE_PHASE_3=<<parameters.ENABLE_PHASE_3>> \
            .circleci/scripts/run-infrastructure.sh '' all-legacy

  start_bichard7_core:
    steps:
      - run: bash scripts/fetch_docker_image.sh nodejs-20-2023 # required for message-forwarder in core
      - build_core_images
      - build_audit_logging_images
      - run:
          command: .circleci/scripts/run-infrastructure.sh '' all-no-worker
          working_directory: ~/bichard7-next-core
      - run:
          # currently quicker to run the worker separately due to data install
          name: Run the worker
          command: npm run -w packages/conductor worker
          working_directory: ~/bichard7-next-core
          background: true

  start_core_testserver:
    steps:
      - run:
          name: Start the test server in the background
          working_directory: ~/bichard7-next-core
          command: npm run -w packages/core test:server
          background: true
      - run:
          name: Wait for Core
          command: npx -y wait-port 6000

#################################################################################

jobs:
  install_and_lint:
    machine:
      image: ubuntu-2204:current
    resource_class: xlarge
    steps:
      - checkout
      - install_ms_edge
      - node_install
      - node/install-packages
      - checkout_core
      - set_locale
      - node/install-packages:
          app-dir: ~/bichard7-next-core
      - run: npm run lint
      - persist_to_workspace:
          root: ~/
          paths: .

  test_e2e:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    parallelism: 10
    parameters:
      next-ui:
        type: boolean
      phase2-core-canary-ratio:
        type: enum
        enum: ["1.0", "0.0"]
      message-entry-point:
        type: enum
        enum: ["mq", "s3"]
      ms-edge:
        type: boolean
    environment:
      RECORD: "true"
      AWS_URL: "http://localhost:4566"
      MESSAGE_ENTRY_POINT: << parameters.message-entry-point >>
      NEXTUI: << parameters.next-ui >>
      PHASE2_CORE_CANARY_RATIO: << parameters.phase2-core-canary-ratio >>
      MS_EDGE: << parameters.ms-edge >>
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - when:
          condition:
            equal: [true, << parameters.ms-edge >>]
          steps:
            - install_ms_edge
      - node_install
      - when:
          condition:
            equal: ["mq", << parameters.message-entry-point >>]
          steps:
            - start_bichard7_legacy
      - when:
          condition:
            equal: ["s3", << parameters.message-entry-point >>]
          steps:
            - start_bichard7_core
      - run_test_chunk
      - save_artifacts
      - store_test_results:
          path: ./cucumber/results

  test_characterisation_legacy_phase1:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - node_install
      - start_bichard7_legacy:
          ENABLE_PHASE_2: "false"
          ENABLE_PHASE_3: "false"
      - run: npm run test:characterisation:bichard:phase1

  test_characterisation_legacy_phase2:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - node_install
      - start_bichard7_legacy:
          ENABLE_PHASE_2: "true"
          ENABLE_PHASE_3: "false"
      - run: npm run test:characterisation:bichard:phase2

  test_characterisation_core:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - node_install
      - start_core_testserver
      - run: npm run test:characterisation

#################################################################################

workflows:
  deploy:
    jobs:
      - install_and_lint

      # Chrome tests
      - test_e2e:
          name: test_e2e_legacy
          next-ui: false
          phase2-core-canary-ratio: "0.0"
          message-entry-point: mq
          ms-edge: false
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_legacy_new_ui
          next-ui: true
          phase2-core-canary-ratio: "0.0"
          message-entry-point: mq
          ms-edge: false
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase1_core
          next-ui: false
          phase2-core-canary-ratio: "0.0"
          message-entry-point: s3
          ms-edge: false
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase1_core_new_ui
          next-ui: true
          phase2-core-canary-ratio: "0.0"
          message-entry-point: s3
          ms-edge: false
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase2_core
          next-ui: false
          phase2-core-canary-ratio: "1.0"
          message-entry-point: s3
          ms-edge: false
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase2_core_new_ui
          next-ui: true
          phase2-core-canary-ratio: "1.0"
          message-entry-point: s3
          ms-edge: false
          requires:
            - install_and_lint

      # MS Edge tests
      - test_e2e:
          name: test_e2e_legacy_ms_edge
          next-ui: false
          phase2-core-canary-ratio: "0.0"
          message-entry-point: mq
          ms-edge: true
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_legacy_new_ui_ms_edge
          next-ui: true
          phase2-core-canary-ratio: "0.0"
          message-entry-point: mq
          ms-edge: true
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase1_core_ms_edge
          next-ui: false
          phase2-core-canary-ratio: "0.0"
          message-entry-point: s3
          ms-edge: true
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase1_core_new_ui_ms_edge
          next-ui: true
          phase2-core-canary-ratio: "0.0"
          message-entry-point: s3
          ms-edge: true
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase2_core_ms_edge
          next-ui: false
          phase2-core-canary-ratio: "1.0"
          message-entry-point: s3
          ms-edge: true
          requires:
            - install_and_lint
      - test_e2e:
          name: test_e2e_phase2_core_new_ui_ms_edge
          next-ui: true
          phase2-core-canary-ratio: "1.0"
          message-entry-point: s3
          ms-edge: true
          requires:
            - install_and_lint

      # Characterisation tests
      - test_characterisation_legacy_phase1:
          requires:
            - install_and_lint
      - test_characterisation_legacy_phase2:
          requires:
            - install_and_lint
      - test_characterisation_core:
          requires:
            - install_and_lint
