version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

commands:
################### Helpers
  save_artifacts:
    steps:
      - run:
          name: Compress the artifacts for easier downloading
          when: always
          command: for file in ./screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - run:
          name: Create the saved_artifacts directory
          when: always
          command: mkdir ./saved_artifacts;
      - run:
          name: Move the gzipped files across
          when: always
          command: mv ./screenshots/*.tar.gz ./saved_artifacts/
      - store_artifacts:
          path: /home/circleci/project/saved_artifacts

  fetch_docker_image:
    parameters:
      image:
        type: string
    steps:
      - run:
          name: Fetch the <<parameters.image>> image
          command: bash scripts/fetch_docker_image.sh <<parameters.image>>

  install_core:
    steps:
      - restore_cache:
          name: Load node_modules from the cache if they haven't changed
          keys:
            - core-deps-{{ checksum "~/bichard7-next-core/package-lock.json" }}
      - run:
          name: NPM install the core repo
          working_directory: cd ~/bichard7-next-core
          command: nvm use v16 && npm i
      - save_cache:
          key: core-deps-{{ checksum "~/bichard7-next-core/package-lock.json" }}
          paths: ~/bichard7-next-core/node_modules
    
  install_tests:
    steps:
      - run:
          name: Create a hash of the package lock
          command: md5sum package-lock.json > package-lock.json.md5
      - restore_cache:
          name: Load node_modules from the cache if they haven't changed
          keys:
            - test-deps-{{ checksum "package-lock.json.md5" }}
      - run:
          name: NPM install the core repo
          command: nvm use v16 && npm i
      - save_cache:
          key: test-deps-{{ checksum "package-lock.json.md5" }}
          paths: node_modules

################### Services
  start_audit_logging:
    description: Run audit logging
    steps:
      - run:
          name: Run audit logging API
          working_directory: ~/bichard7-next-audit-logging
          command: npm install && SKIP_PG=true SKIP_MQ=true npm run start-api
          background: true
      - run:
          name: Wait for Audit logging API to start
          command: npx wait-on http://localhost:3010/messages

  start_bichard7:
    parameters:
      ENABLE_PHASE_2:
        default: "true"
        type: string
    steps:
      - install_core
      - start_audit_logging
      - fetch_docker_image:
          image: nodejs # required for message-forwarder in core
      - run:
          name: Run docker services
          working_directory: ~/bichard7-next-core
          command: ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> npm run all-no-worker
      - run:
          name: Retry - run docker services
          working_directory: ~/bichard7-next-core
          when: on_fail
          command: |
            npm run destroy
            ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> npm run all-no-worker

  start_core:
    steps:
      - install_core
      - run:
          name: Start the test server in the background
          working_directory: ~/bichard7-next-core
          command: nvm use v16 && npm run test:server
          background: true
      - run:
          name: Wait for Core
          command: nvm use v16 && npx -y wait-port 6000

################### Tests
  test_chunk:
    steps:
      - run:
          name: Install E2E tests
          command: npm i
      - run:
          name: Run E2E tests
          environment:
          command: TOTAL_CHUNKS=$CIRCLE_NODE_TOTAL CHUNK_NUMBER=$CIRCLE_NODE_INDEX npm run test:chunk

  test_chunk_nextui:
    steps:
      - run:
          name: Install E2E tests
          command: npm i
      - run:
          name: Run E2E tests with next UI
          command: TOTAL_CHUNKS=$CIRCLE_NODE_TOTAL CHUNK_NUMBER=$CIRCLE_NODE_INDEX npm run test:chunk:nextUI

  test_characterisation_core:
    steps:
      - install_tests
      - run: nvm use v16 && npm run test:characterisation

  test_characterisation_bichard:
    steps:
      - install_tests
      - run: nvm use v16 && npm run test:characterisation:bichard

################### Job definitions
  run-tests-e2e:
    steps:
      - start_bichard7
      - test_chunk
      - save_artifacts

  run-tests-e2e-nextui:
    steps:
      - start_bichard7
      - test_chunk_nextui
      - save_artifacts

  run-tests-characterisation-bichard:
    steps:
      - start_bichard7:
          ENABLE_PHASE_2: "false"
      - test_characterisation_bichard

  run-tests-characterisation-core:
    steps:
      - start_core
      - test_characterisation_core

#################################################################################

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    resource_class: xlarge
    steps:
      - add_ssh_keys:
          fingerprints:
            - 15:7c:72:90:e7:44:01:0e:3d:a3:fc:b5:ca:c0:c2:f3
      - checkout
      - persist_to_workspace:
          root: ~/
          paths: project
      - run:
          name: Clone bichard7-next-core
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next-core.git ~/bichard7-next-core
      - persist_to_workspace:
          root: ~/
          paths: bichard7-next-core
      - run:
          name: Clone bichard7-next-audit-logging
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next-audit-logging.git ~/bichard7-next-audit-logging
      - persist_to_workspace:
          root: ~/
          paths: bichard7-next-audit-logging

  test-e2e:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    resource_class: large
    environment:
      RECORD: "true"
    steps:
      - attach_workspace:
          at: ~/
      - run-tests-e2e
    parallelism: 10

  tests-e2e-new-ui:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    resource_class: large
    environment:
      RECORD: "true"
    steps:
      - attach_workspace:
          at: ~/
      - run-tests-e2e-nextui
    parallelism: 10

  test-characterisation-bichard:
    machine:
        image: ubuntu-2004:2022.07.1
        docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - run-tests-characterisation-bichard

  test-characterisation-core:
    machine:
        image: ubuntu-2004:2022.07.1
        docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - run-tests-characterisation-core

#################################################################################

workflows:
  version: 3

  deploy:
    jobs:
      - build
      - test-e2e:
          requires:
            - build
      - tests-e2e-new-ui:
          requires:
            - build
      - test-characterisation-bichard:
          requires:
            - build
      - test-characterisation-core:
          requires:
            - build
