version: 2.1

orbs:
  node: circleci/node@5.2.0

commands:
  ################### Helpers
  checkout_core:
    steps:
      - run:
          name: Clone bichard7-next-core
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-core.git ~/bichard7-next-core
      - run:
          name: Install dependency
          working_directory: ~/bichard7-next-core
          command: npm i
      - run:
          name: Build core
          working_directory: ~/bichard7-next-core
          command: npm run build

  build_core_images:
    steps:
      - run:
          name: Build message forwarder image
          working_directory: ~/bichard7-next-core
          command: docker-compose -f environment/docker-compose.yml build phase-1-message-forwarder phase-2-message-forwarder

  build_audit_logging_images:
    steps:
      - run:
          name: Clone bichard7-next-audit-logging
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-audit-logging.git ~/bichard7-next-audit-logging
      - run:
          name: Build audit logging images
          working_directory: ~/bichard7-next-audit-logging
          command: make build-api-server build-event-handler-server

  node_install:
    steps:
      - restore_cache:
          name: Restore nvm cache
          keys:
            # Invalidate the cache based on architecture, the version of Node defined in `nvmrc`
            - v1-nvm-cache-{{ arch }}-{{ checksum ".nvmrc" }}
      - run: nvm install
      - save_cache:
          name: Save nvm cache
          key: v1-nvm-cache-{{ arch }}-{{ checksum ".nvmrc" }}
          paths:
            - /opt/circleci/.nvm/.cache

  ################### Services
  start_bichard7_legacy:
    parameters:
      ENABLE_PHASE_2:
        default: "true"
        type: string
      ENABLE_PHASE_3:
        default: "true"
        type: string
    steps:
      - run: bash scripts/fetch_docker_image.sh nodejs-20-2023 # required for message-forwarder in core
      - build_core_images
      - build_audit_logging_images
      - run:
          name: Start bichard7 legacy
          working_directory: ~/bichard7-next-core
          command: |
            ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> ENABLE_PHASE_3=<<parameters.ENABLE_PHASE_3>> \
            .circleci/scripts/run-infrastructure.sh '' all-legacy

  start_bichard7_core:
    steps:
      - run: bash scripts/fetch_docker_image.sh nodejs-20-2023 # required for message-forwarder in core
      - build_core_images
      - build_audit_logging_images
      - run:
          command: .circleci/scripts/run-infrastructure.sh '' all-no-worker
          working_directory: ~/bichard7-next-core
      - run:
          # currently quicker to run the worker separately due to data install
          name: Run the worker
          command: npm run -w packages/conductor worker
          working_directory: ~/bichard7-next-core
          background: true

  start_core_testserver:
    steps:
      - run:
          name: Start the test server in the background
          working_directory: ~/bichard7-next-core
          command: npm run -w packages/core test:server
          background: true
      - run:
          name: Wait for Core
          command: npx -y wait-port 6000

#################################################################################

jobs:
  install_and_lint:
    machine:
      image: ubuntu-2204:current
    resource_class: xlarge
    steps:
      - checkout
      - node_install
      - node/install-packages
      - checkout_core
      - node/install-packages:
          app-dir: ~/bichard7-next-core
      - run: npm run lint
      - run: npm run check
      - persist_to_workspace:
          root: ~/
          paths: .

  test_characterisation_legacy_phase1:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - node_install
      - start_bichard7_legacy:
          ENABLE_PHASE_2: "false"
          ENABLE_PHASE_3: "false"
      - run: npm run test:characterisation:bichard:phase1

  test_characterisation_legacy_phase2:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - node_install
      - start_bichard7_legacy:
          ENABLE_PHASE_2: "true"
          ENABLE_PHASE_3: "false"
      - run: npm run test:characterisation:bichard:phase2

  test_characterisation_core:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - node_install
      - start_core_testserver
      - run: npm run test:characterisation

#################################################################################

workflows:
  deploy:
    jobs:
      - install_and_lint
      # Characterisation tests
      - test_characterisation_legacy_phase1:
          requires:
            - install_and_lint
      - test_characterisation_legacy_phase2:
          requires:
            - install_and_lint
      - test_characterisation_core:
          requires:
            - install_and_lint
