version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

commands:
################### Helpers
  fetch_docker_image:
    parameters:
      image:
        type: string
    steps:
      - run:
          name: Fetch the <<parameters.image>> image
          command: bash scripts/fetch_docker_image.sh <<parameters.image>>

  install_tests:
    steps:
      - checkout
      - restore_cache:
          name: Check cache for test NPM dependencies
          keys:
            - bichard7-next-tests-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install test NPM dependencies
          command: nvm use v16 && npm i
      - save_cache:
          key: bichard7-next-tests-deps-{{ checksum "package-lock.json" }}
          paths: node_modules

  install_core:
    steps:
      - run:
          name: Clone bichard7-next-core
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-core.git ~/bichard7-next-core
      - restore_cache:
          name: Check cache for core NPM dependencies
          keys:
            - bichard7-next-core-deps-{{ checksum "~/bichard7-next-core/package-lock.json" }}
      - run:
          name: Install core NPM dependencies
          command: cd ~/bichard7-next-core && nvm use v16 && npm i
      - save_cache:
          key: bichard7-next-core-deps-{{ checksum "~/bichard7-next-core/package-lock.json" }}
          paths: ~/bichard7-next-core/node_modules

  save_artifacts:
    steps:
      - run:
          name: Compress the artifacts for easier downloading
          when: always
          command: for file in ./screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - run:
          name: Create the saved_artifacts directory
          when: always
          command: mkdir ./saved_artifacts;
      - run:
          name: Move the gzipped files across
          when: always
          command: mv ./screenshots/*.tar.gz ./saved_artifacts/
      - store_artifacts:
          path: /home/circleci/project/saved_artifacts

################### Services
  start_bichard7:
    parameters:
      ENABLE_PHASE_2:
        default: "true"
        type: string
    steps:
      - fetch_docker_image:
          image: nodejs # required for message-forwarder in core
      - run:
          name: Run docker services
          working_directory: ~/bichard7-next-core
          command: ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> npm run all-no-worker
      - run:
          name: Retry - run docker services
          working_directory: ~/bichard7-next-core
          when: on_fail
          command: |
            npm run destroy
            ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> npm run all-no-worker

  start_core:
    steps:
      - run:
          name: Start the test server in the background
          working_directory: ~/bichard7-next-core
          command: nvm use v16 && npm run test:server
          background: true
      - run:
          name: Wait for Core
          command: nvm use v16 && npx -y wait-port 6000

#################################################################################

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    resource_class: xlarge
    steps:
      - install_tests
      - install_core
      - persist_to_workspace:
          root: ~/
          paths: .

  test-e2e:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: true
    resource_class: large
    environment:
      RECORD: "true"
    steps:
      - attach_workspace:
          at: ~/
      - start_bichard7
      - run: TOTAL_CHUNKS=$CIRCLE_NODE_TOTAL CHUNK_NUMBER=$CIRCLE_NODE_INDEX npm run test:chunk
      - save_artifacts
    parallelism: 10

  tests-e2e-new-ui:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: true
    resource_class: large
    environment:
      RECORD: "true"
    steps:
      - attach_workspace:
          at: ~/
      - start_bichard7
      - run: TOTAL_CHUNKS=$CIRCLE_NODE_TOTAL CHUNK_NUMBER=$CIRCLE_NODE_INDEX npm run test:chunk:nextUI
      - save_artifacts
    parallelism: 10

  test-characterisation-bichard:
    machine:
        image: ubuntu-2004:2022.07.1
        docker_layer_caching: true
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - start_bichard7:
          ENABLE_PHASE_2: "false"
      - run: nvm use v16 && npm run test:characterisation:bichard

  test-characterisation-core:
    machine:
        image: ubuntu-2004:2022.07.1
        docker_layer_caching: true
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - start_core
      - run: nvm use v16 && npm run test:characterisation

#################################################################################

workflows:
  version: 3

  deploy:
    jobs:
      - build
      - test-e2e:
          requires:
            - build
      - tests-e2e-new-ui:
          requires:
            - build
      - test-characterisation-bichard:
          requires:
            - build
      - test-characterisation-core:
          requires:
            - build
