version: 2.1

orbs:
  node: circleci/node@5.2.0

commands:
  ################### Helpers
  checkout_core:
    steps:
      - run:
          name: Clone bichard7-next-core
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-core.git ~/bichard7-next-core
      - run:
          name: Install dependency
          working_directory: ~/bichard7-next-core
          command: npm i
      - run:
          name: Build core
          working_directory: ~/bichard7-next-core
          command: npm run build

  build_core_images:
    steps:
      - run:
          name: Build message forwarder image
          working_directory: ~/bichard7-next-core
          command: docker-compose -f environment/docker-compose.yml build message-forwarder

  build_audit_logging_images:
    steps:
      - run:
          name: Clone bichard7-next-audit-logging
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-audit-logging.git ~/bichard7-next-audit-logging
      - run:
          name: Build audit logging images
          working_directory: ~/bichard7-next-audit-logging
          command: make build-api-server build-event-handler-server

  run_test_chunk:
    steps:
      - run:
          name: Run test chunk
          command: |
            CHUNK=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings) \
            npm run test:chunk

  save_artifacts:
    steps:
      - run:
          name: Compress the artifacts for easier downloading
          when: always
          command: for file in ./screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - run:
          name: Create the saved_artifacts directory
          when: always
          command: mkdir ./saved_artifacts;
      - run:
          name: Move the gzipped files across
          when: always
          command: mv ./screenshots/*.tar.gz ./saved_artifacts/
      - store_artifacts:
          path: /home/circleci/project/saved_artifacts
      - store_test_results:
          path: /home/circleci/project/test-results.xml

  node_install:
    steps:
      - restore_cache:
          name: Restore nvm cache
          keys:
            # Invalidate the cache based on architecture, the version of Node defined in `nvmrc`
            - v1-nvm-cache-{{ arch }}-{{ checksum ".nvmrc" }}
      - run: nvm install
      - save_cache:
          name: Save nvm cache
          key: v1-nvm-cache-{{ arch }}-{{ checksum ".nvmrc" }}
          paths:
            - /opt/circleci/.nvm/.cache

  set_locale:
    steps:
      - run:
          name: Set GB locale
          working_directory: ~/bichard7-next-core
          command: bash .circleci/scripts/set-locale.sh

  ################### Services
  start_bichard7_legacy:
    parameters:
      ENABLE_PHASE_2:
        default: "true"
        type: string
    steps:
      - run: bash scripts/fetch_docker_image.sh nodejs-20-2023 # required for message-forwarder in core
      - build_core_images
      - build_audit_logging_images
      - run:
          name: Start bichard7 legacy
          working_directory: ~/bichard7-next-core
          command: |
            ENABLE_PHASE_2=<<parameters.ENABLE_PHASE_2>> \
            .circleci/scripts/run-infrastructure.sh '' all-legacy

  start_bichard7_core:
    steps:
      - run: bash scripts/fetch_docker_image.sh nodejs-20-2023 # required for message-forwarder in core
      - build_core_images
      - build_audit_logging_images
      - run:
          command: .circleci/scripts/run-infrastructure.sh '' all-no-worker
          working_directory: ~/bichard7-next-core
      - run:
          # currently quicker to run the worker separately due to data install
          name: Run the worker
          command: npm run -w packages/conductor worker
          working_directory: ~/bichard7-next-core
          background: true

  start_core_testserver:
    steps:
      - run:
          name: Start the test server in the background
          working_directory: ~/bichard7-next-core
          command: npm run -w packages/core test:server
          background: true
      - run:
          name: Wait for Core
          command: npx -y wait-port 6000

#################################################################################

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: xlarge
    steps:
      - checkout
      - node_install
      - node/install-packages
      - checkout_core
      - set_locale
      - node/install-packages:
          app-dir: ~/bichard7-next-core
      - persist_to_workspace:
          root: ~/
          paths: .

  test-e2e:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    parallelism: 10
    parameters:
      nextUi:
        type: boolean
      phase2CoreCanaryRatio:
        type: enum
        enum: ["1.0", "0.0"]
      messageEntryPoint:
        type: enum
        enum: ["mq", "s3"]
    environment:
      RECORD: "true"
      AWS_URL: "http://localhost:4566"
      MESSAGE_ENTRY_POINT: << parameters.messageEntryPoint >>
      NEXTUI: << parameters.nextUi >>
      PHASE2_CORE_CANARY_RATIO: << parameters.phase2CoreCanaryRatio >>
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - node_install
      - when:
          condition:
            equal: [ "mq", << parameters.messageEntryPoint >> ]
          steps:
            - start_bichard7_legacy
      - when:
          condition:
            equal: [ "s3", << parameters.messageEntryPoint >> ]
          steps:
          - start_bichard7_core
      - run_test_chunk
      - save_artifacts
      - store_test_results:
          path: ./cucumber/results

  test-characterisation-legacy:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - node_install
      - start_bichard7_legacy:
          ENABLE_PHASE_2: "false"
      - run: npm run test:characterisation:bichard

  test-characterisation-core:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - attach_workspace:
          at: ~/
      - set_locale
      - node_install
      - start_core_testserver
      - run: npm run test:characterisation

#################################################################################

workflows:
  deploy:
    jobs:
      - build
      - test-e2e:
          name: test-e2e-legacy
          nextUi: false
          phase2CoreCanaryRatio: "0.0"
          messageEntryPoint: mq
          requires:
            - build
      - test-e2e:
          name: test-e2e-legacy-new-ui
          nextUi: true
          phase2CoreCanaryRatio: "0.0"
          messageEntryPoint: mq
          requires:
            - build
      - test-e2e:
          name: test-e2e-core
          nextUi: false
          phase2CoreCanaryRatio: "0.0"
          messageEntryPoint: s3
          requires:
            - build
      - test-e2e:
          name: test-e2e-core-new-ui
          nextUi: true
          phase2CoreCanaryRatio: "0.0"
          messageEntryPoint: s3
          requires:
            - build
      - test-e2e:
          name: test-e2e-phase2-core
          nextUi: false
          phase2CoreCanaryRatio: "1.0"
          messageEntryPoint: s3
          requires:
            - build
      - test-e2e:
          name: test-e2e-phase2-core-new-ui
          nextUi: true
          phase2CoreCanaryRatio: "1.0"
          messageEntryPoint: s3
          requires:
            - build
      - test-characterisation-legacy:
          requires:
            - build
      - test-characterisation-core:
          requires:
            - build
